---
substitutions:
  device_name: sprinklers
  device_description: "DIY Sprinklers system"

esphome:
  name: ${device_name}
  comment: "${device_description}"

esp8266:
  board: esp01_1m
  # name_add_mac_suffix: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  # manual_ip:
    # static_ip: !secret sprinklers_ip
    # gateway: !secret iot_gateway
    # subnet: !secret iot_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}

captive_portal:

web_server:
  port: 80

logger:
  baud_rate: 0 #need this to free up UART pins

sensor:
  - platform: uptime
    name: "Sprinkler uptime"
    update_interval: 60s
    id: uptime_sensor
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s

text_sensor:
  - platform: version
    name: Sprinkler Version
  - platform: wifi_info
    ip_address:
      name: "Sprinkler IP"
    ssid:
      name: "Sprinkler SSID"
    bssid:
      name: "Sprinkler BSSID"
  - platform: template
    name: Sprinkler Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start

uart:
  baud_rate: 115200 # speed to STC15L101EW
  tx_pin: GPIO1
  rx_pin: GPIO3

switch:
  - platform: template
    name: 'Zone 1'
    id: relay1
    turn_on_action:
      - uart.write: [0xA0, 0x01, 0x01, 0xA2]
    turn_off_action:
      - uart.write: [0xA0, 0x01, 0x00, 0xA1]
    optimistic: true
  - platform: template
    name: 'Zone 2'
    id: relay2
    turn_on_action:
      - uart.write: [0xA0, 0x02, 0x01, 0xA3]
    turn_off_action:
      - uart.write: [0xA0, 0x02, 0x00, 0xA2]
    optimistic: true
  - platform: template
    name: 'Zone 3'
    id: relay3
    turn_on_action:
      - uart.write: [0xA0, 0x03, 0x01, 0xA4]
    turn_off_action:
      - uart.write: [0xA0, 0x03, 0x00, 0xA3]
    optimistic: true
  - platform: template
    name: 'Zone 4'
    id: relay4
    turn_on_action:
      - uart.write: [0xA0, 0x04, 0x01, 0xA5]
    turn_off_action:
      - uart.write: [0xA0, 0x04, 0x00, 0xA4]
    optimistic: true
  - platform: restart
    name: "Sprinkler restart"

# Enable Home Assistant API
api:
  encryption: 
    key: !secret sprinklers_encryption_key

ota:
  platform: esphome
  password: !secret sprinklers_ota_password
