---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    name: üßπ yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ‚§µÔ∏è Check out configuration from GitHub
        uses: actions/checkout@v6
      - name: üöÄ Run yamllint
        uses: frenck/action-yamllint@v1.5

  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: ‚§µÔ∏è Check out configuration from GitHub
        uses: actions/checkout@v6
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    needs: [yamllint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Create fake empty files
        run: |
          touch ./home-assistant_v2.db
          touch ./home-assistant.log
      - name: Create empty custom components folder
        run: |
          mkdir -p ./custom_components
      - name: Clone custom component Brandstofprijzen
        run: |
          git clone https://github.com/metbril/home-assistant-brandstofprijzen.git
          rm -rf ./custom_components/brandstofprijzen
          cp -rv home-assistant-brandstofprijzen/custom_components/. ./custom_components/
      - name: Clone custom component Unifi protect
        run: |
          git clone https://github.com/briis/unifiprotect
          rm -rf ./custom_components/unifiprotect
          cp -rv unifiprotect/custom_components/. ./custom_components/
      - name: Clone custom component Browser mod
        run: |
          git clone https://github.com/thomasloven/hass-browser_mod
          rm -rf ./custom_components/browser_mod
          cp -rv hass-browser_mod/custom_components/. ./custom_components/
      - name: Clone custom component Spotcast
        run: |
          git clone https://github.com/fondberg/spotcast
          rm -rf ./custom_components/spotcast
          cp -rv spotcast/custom_components/. ./custom_components/
      - name: Clone custom component Afvalwijzer
        run: |
          git clone https://github.com/xirixiz/homeassistant-afvalwijzer
          rm -rf ./custom_components/afvalwijzer
          cp -rv homeassistant-afvalwijzer/custom_components/. ./custom_components/
      - name: Clone custom component Xiaomi map cloud extractor
        run: |
          git clone https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
          rm -rf ./custom_components/xiaomi_cloud_map_extractor
          cp -rv Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/custom_components/. ./custom_components/
      - name: Clone custom component Irrigation Unlimited
        run: |
          git clone https://github.com/rgc99/irrigation_unlimited
          rm -rf ./custom_components/irrigation_unlimited
          cp -rv irrigation_unlimited/custom_components/. ./custom_components/
      - name: Clone custom component Powercalc
        run: |
          git clone https://github.com/bramstroker/homeassistant-powercalc
          rm -rf ./custom_components/powercalc
          cp -rv homeassistant-powercalc/custom_components/. ./custom_components/
      - name: Clone custom component unifigateway
        run: |
          git clone https://github.com/custom-components/sensor.unifigateway
          rm -rf ./custom_components/unifigateway
          cp -rv sensor.unifigateway/custom_components/. ./custom_components/
      - name: Clone custom component wundergroundpws
        run: |
          git clone https://github.com/cytech/Home-Assistant-wundergroundpws
          rm -rf ./custom_components/wundergroundpws
          cp -rv Home-Assistant-wundergroundpws/custom_components/. ./custom_components/
      - name: Clone custom component formulaone_api
        run: |
          git clone https://github.com/delzear/hass-formulaoneapi
          rm -rf ./custom_components/formulaone_api
          cp -rv hass-formulaoneapi/custom_components/. ./custom_components/
      - name: Clone custom component Gotify
        run: |
          git clone https://github.com/1RandomDev/homeassistant-gotify.git
          rm -rf ./custom_components/gotify
          cp -rv homeassistant-gotify/custom_components/. ./custom_components/
      - name: Check configuration
        uses: frenck/action-home-assistant@v1.4
        with:
          secrets: ./.stubs/ci_secrets.yaml
          version: "${{ matrix.version }}"
